### ISSUE TITLE
When installing npm modules put them into package.json to reduce number of commands?

### ISSUE THREAD

**Issue by stefek99** [decentraland/decentraland-node#53] opened 2017-06-28 07:32 UTC
Currently:

```
npm install
npm install bn.js elliptic mkdirp webtorrent-hybrid create-torrent parse-torrent socket.io-client leveldown express cors
```

It should be possible to change `package.json` and do the same with the lower number of clicks?

**Comment by HPrivakos** [comment] 2017-06-28 13:58
It's already in the package.json =)

**Comment by stefek99** [comment] 2017-06-28 14:31
I see... I'm just a human, when I see "Getting Started" instructions I do not overthink too much.

**Comment by ghost** [comment] 2017-06-28 14:38
Hi guys - I added these to the Windows instructions in my PR #46 to add Windows support yesterday. Did it because the `npm install` for whatever reason didn't install all required modules. I've also seen this on Linux.

Not sure how to fix that but figured it's better-than-nothing to have it in the docs. So at least you can handle it in the install process rather than hitting errors later and needing to fix them.

I agree this should be fixed so `npm install` handles everything.

**Comment by stefek99** [comment] 2017-06-28 16:17
> Did it because the npm install for whatever reason didn't install all required modules. 

I'll make the effort to open my Windows laptop and try it out.

**Comment by martriay** [comment] 2017-06-29 05:07
@stefek99 could you reproduce this?

**Comment by stefek99** [comment] 2017-06-29 12:56
@martriay 

This is my work machine with old `node` and no `python`... Super busy, I won't be able to access my Windows laptop at least till Monday.

_(I'll try to set up a VM)_

![image](https://user-images.githubusercontent.com/249703/27688510-b4b337ca-5cd2-11e7-84d7-784f432f6d11.png)

**Comment by HPrivakos** [comment] 2017-06-29 13:06
Read the README, node v7 required

[https://github.com/decentraland/bronzeage-node#run-a-node-manually-on-linux](https://github.com/decentraland/bronzeage-node#run-a-node-manually-on-linux)

> Install NodeJS. The current decentraland node requires NodeJS v7.4.0 or higher. See nvm for version management.

**Comment by stefek99** [comment] 2017-06-29 13:57
Of course I read the README and of course I know that newer version of node is required.

That is why I said:

> my work machine with **old node**

No worries, the `.iso` download is completed, I can try to reproduce the issue.

**Closed as completed** 2017-07-27 00:38 UTC
